-- 学生表
CREATE TABLE student
(
sno VARCHAR(3) NOT NULL PRIMARY KEY,
sname VARCHAR(4) NOT NULL,
ssex VARCHAR(2) NOT NULL,
sbirthday DATETIME NOT NULL,
class VARCHAR(5)
);
-- 课程表
CREATE TABLE course
(
cno VARCHAR(5) NOT NULL PRIMARY KEY,
cname VARCHAR(10) NOT NULL,
tno VARCHAR(10) NOT NULL
);
-- 成绩表
CREATE TABLE score
(
sno VARCHAR(3) NOT NULL,
cno VARCHAR(5) NOT NULL,
degree NUMERIC(10,1) NOT NULL
);
-- 教师表
CREATE TABLE teacher
(
tno VARCHAR(3) NOT NULL PRIMARY KEY,
tname VARCHAR(4) NOT NULL,
tsex VARCHAR(2) NOT NULL,
tbirthday DATETIME NOT NULL,
prof VARCHAR(6) NOT NULL,
depart VARCHAR(10) NOT NULL
);
